version: "3"
services:
  wordpress_sql:
    image: mysql:latest
    container_name: wordpress_sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
 
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - 50001:80
    environment:
      WORDPRESS_DB_HOST: wordpress_sql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
